### ISSUE TITLE
'This product does not have a registered Bunifu UI license to run.'

### ISSUE THREAD

**Issue by yuhkix** [SheratoD/.Net-Libs#1]
Hey, so as the Title says I'm being told that the products I'm using dont have a registered Bunifu license even though I replaced the licensing dll in both lib folders of the Bunifu.Licensing package, any idea what I've done wrong?

Thanks in advance :)

**Comment by SheratoD** [comment]
Hi, after installing the nuget you have to look for Bunifu Licencing dll inside your project files and replace it with mine, then you have to restart the project (reopen the project), if you still need help I can make you a video.

**Comment by SheratoD** [comment]
Sorry, my bad, apparently they have updated Bunifu.Licencing to version 5.0.0.0.0 and mine is 4.0.0.0.0, let me try to crack the new version.

**Comment by SheratoD** [comment]
Sorry I forgot to explain that you just fill in the blanks with whatever and hit activate, thanks for your comment I will work on getting it to activate itself so you don't have to do it manually.
